//tag::ref-doc[]
= Twitter Stream Source

This source ingests data from Twitter's https://dev.twitter.com/docs/streaming-apis/streams/public[streaming API v1.1]. It uses the https://dev.twitter.com/docs/streaming-apis/streams/public[sample and filter] stream endpoints rather than the full "firehose" which needs special access. The endpoint used will depend on the parameters you supply in the stream definition (some are specific to the filter endpoint).

You need to supply all keys and secrets (both consumer and accessToken) to authenticate for this source, so it is easiest if you just add these as the following environment variables: CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN and ACCESS_TOKEN_SECRET.

== Options

The **$$twitterstream$$** $$source$$ has the following options:

//tag::configuration-properties[]
$$twitter.credentials.access-token$$:: $$Access token$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.credentials.access-token-secret$$:: $$Access token secret$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.credentials.consumer-key$$:: $$Consumer key$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.credentials.consumer-secret$$:: $$Consumer secret$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.stream.language$$:: $$The language of the tweet text.$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.stream.stream-type$$:: $$Twitter stream type (such as sample, firehose). Default is sample.$$ *($$TwitterStreamType$$, default: `$$<none>$$`, possible values: `SAMPLE`,`FIREHOSE`)*
//end::configuration-properties[]

NOTE: `twitterstream` emit JSON in the https://dev.twitter.com/docs/platform-objects/tweets[native Twitter format].

//end::ref-doc[]
== Build

```
$ mvn clean package
```

