//tag::ref-doc[]
= Twitter Stream Source

This source ingests data from Twitter's https://dev.twitter.com/docs/streaming-apis/streams/public[streaming API v1.1]. It uses the https://dev.twitter.com/docs/streaming-apis/streams/public[sample and filter] stream endpoints rather than the full "firehose" which needs special access. The endpoint used will depend on the parameters you supply in the stream definition (some are specific to the filter endpoint).

You need to supply all keys and secrets (both consumer and accessToken) to authenticate for this source, so it is easiest if you just add these as the following environment variables: CONSUMER_KEY, CONSUMER_SECRET, ACCESS_TOKEN and ACCESS_TOKEN_SECRET.

== Input

N/A

== Output

=== Headers

* `Content-Type: text/plain`

=== Payload

* `String`

== Options

The **$$twitterstream$$** $$source$$ has the following options:

//tag::configuration-properties[]
$$twitter.credentials.access-token$$:: $$Access token$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.credentials.access-token-secret$$:: $$Access token secret$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.credentials.consumer-key$$:: $$Consumer key$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.credentials.consumer-secret$$:: $$Consumer secret$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.stream.filter.follow$$:: $$A comma separated list of user IDs, indicating the users to return statuses for in the stream.$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.stream.filter.locations$$:: $$A set of bounding boxes to track.$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.stream.filter.stream-type$$:: $$Twitter stream type (such as sample, firehose). Default is sample.$$ *($$TwitterStreamType$$, default: `$$<none>$$`, possible values: `SAMPLE`,`FIREHOSE`,`FILTER`)*
$$twitter.stream.filter.track$$:: $$Keywords to track.$$ *($$String$$, default: `$$<none>$$`)*
$$twitter.stream.language$$:: $$The language of the tweet text.$$ *($$String$$, default: `$$<none>$$`)*
//end::configuration-properties[]

NOTE: `twitterstream` emit JSON in the https://dev.twitter.com/docs/platform-objects/tweets[native Twitter format].

== Build

```
$ ./mvnw clean install -PgenerateApps
$ cd apps
```
You can find the corresponding binder based projects here.
You can then cd into one one of the folders and build it:
```
$ ./mvnw clean package
```

== Examples

```
java -jar twitter_stream_source.jar --consumerKey=<CONSUMER_KEY> --consumerSecret=<CONSUMER_SECRET> \
    --accessToken=<ACCESS_TOKEN> --accessTokenSecret=<ACCESS_TOKEN_SECRET>
```

//end::ref-doc[]
